// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsSSYPK-JDNVA04nKQC9yrcGsNzLkOfNc',
    appId: '1:1038358532871:android:7cb43728c04839c3162ba2',
    messagingSenderId: '1038358532871',
    projectId: 'famat-c5559',
    storageBucket: 'famat-c5559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGoLM2AaiC5sXXLMIA2BTpmL4qgj-80Tw',
    appId: '1:1038358532871:ios:293d03d42fd84d61162ba2',
    messagingSenderId: '1038358532871',
    projectId: 'famat-c5559',
    storageBucket: 'famat-c5559.appspot.com',
    androidClientId: '1038358532871-rhadvnvp42b304fq7hkkfa5jm593h77j.apps.googleusercontent.com',
    iosClientId: '1038358532871-acn49tvkhb5273cctss6g83h7nvbtjie.apps.googleusercontent.com',
    iosBundleId: 'com.example.famet',
  );
}
